version: "3.9"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_VERSION_NUMBER: 1.4
    restart: unless-stopped
    container_name: aurora_front
    ports:
      - 3001:3000
