version: '3.9' # Docker Engine release 19.03.0+ [https://docs.docker.com/compose/compose-file/]

services:
    # setup MongoDB cluster for production
    web:
        build: aurora
        restart: always
        container_name: aurora_front
        ports:
            - 5001:3000

    mongo1:
        container_name: 'mongo-db'
        image: 'mongo:4.2'
        restart: 'on-failure'
        expose:
            - 27017
        ports:
            - 30001:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: db
