FROM node@sha256:0324faef815aea5b6d84c988f8cc3ca16169203944e01fdb79e90c747f4a36e0

ARG NEXT_PUBLIC_VERSION_NUMBER
ENV NEXT_PUBLIC_VERSION_NUMBER=${NEXT_PUBLIC_VERSION_NUMBER}
RUN mkdir -p /home/app/ && chown -R node:node /home/app
WORKDIR /home/app
COPY --chown=node:node . .

USER node
ENV NEXT_TELEMETRY_DISABLED 1
ENV HOSTNAME "0.0.0.0"

RUN npm ci
RUN npm run build
EXPOSE 3000
CMD [ "npm", "start" ]