version: '3'
services:
    web:
        build: .
        restart: always
        container_name: aurora_front
        ports:
            - 5001:3000
    mongo:
        image: mongo:latest
        restart: always
        container_name: mongo
        ports:
            - 27017:27017
