import type { NextPage } from 'next';
import Head from 'next/head';
import {
    About,
    Contact,
    Experience,
    LandingPage,
    Work,
} from '../components/index';
import { ProjectInterface } from '../components/work/Work';
import { GITHUB_PROJECTS_URL } from '../config.json';
import styles from '../styles/Home.module.css';

export interface Props {}

export default function Home({ projects }: { projects: ProjectInterface[] }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Aurora </title>
                <meta
                    name="description"
                    content="Generated by create next app, made by FO"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <LandingPage />
                <About />
                <Experience />
                <Work projects={projects} />
                <Contact />
            </main>
        </div>
    );
}

export async function getStaticProps() {
    let dataResponse;
    const response = await fetch(GITHUB_PROJECTS_URL);
    if (response.status >= 200 && response.status <= 299) {
        const jsonResponse = await response.json();
        dataResponse = {
            props: { projects: jsonResponse.projects },
            revalidate: process.env.REVALIDATE_VALUE,
        };
    } else {
        console.log(response.status);
        dataResponse = {
            props: { projects: [] },
            revalidate: process.env.REVALIDATE_VALUE,
        };
    }

    return dataResponse;
}
