# If a new version is published against main branch, build a new docker image and push it to docker hub
name: Publish LIVE Docker image

on:
  release:
    branches:
      - main
    types:
      - published

env:
  VERSION_TAG: ${{ github.event.release.tag_name }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PROJECT_NAME: aurora

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Image
        run: |
          docker build \
          -t $DOCKER_USERNAME/$PROJECT_NAME:$VERSION_TAG \
          -t $DOCKER_USERNAME/$PROJECT_NAME:latest \
          -f ./Dockerfile \
          ./
      - name: Push Image
        run: |
          docker push --all-tags $DOCKER_USERNAME/$PROJECT_NAME